import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import LoadingPage from "./loading";
import { AuthProvider } from "@/context/auth-context";

const interSans = Inter({
	variable: "--font-inter-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${interSans.variable} antialiased`}>
				<AuthProvider>
					<Suspense fallback={<LoadingPage />}>
						{children}
					</Suspense>
				</AuthProvider>
			</body>
		</html>
	);
}
