# Generated by Django 6.0 on 2025-12-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_book_coverurl_book_genre_book_isbn_book_onbookshelf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='book',
            name='onBookshelf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read',
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('onBookshelf', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_marks', to='booklist.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Book Mark',
                'verbose_name_plural': 'User Book Marks',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
